### ISSUE TITLE
search-drawer (textbox) overflows drawer

### ISSUE THREAD

**Issue by chucklorenz** [cgkineo/adapt-search#35]
The search-drawer contains the text input. It overflows the drawer on iPhone and IE11 as seen in the image below. search.less assigns 'initial' to 'width'.
```less
.search-drawer {
    width: initial !important;
    &:hover {
        background-color:initial !important;
    }
}
```
 [IE11 doesn't recognize 'initial'](https://msdn.microsoft.com/en-us/library/ms531183(v=vs.85).aspx); and, apparently, iOS has some issue with the current Less. Both were fixed by using 'auto' instead of 'initial'. A quick, incomprehensive check with the browsers I had on hand, showed desktop browsers worked just fine with 'auto' instead of 'initial'.  

![image-20170917-215516](https://user-images.githubusercontent.com/9489014/30655606-1afefc70-9df7-11e7-9868-01e0cfe064bc.png)
